### ISSUE TITLE
const rate = 2;

### ISSUE THREAD

**Issue by q82415670** [fw567/RainclassRoom#1]
调到2了并不会自动倍速

**Comment by q82415670** [comment]
还有 看完的视频不会自动关闭，如果挂一宿的话会多出好多好多网页吧，如果顺序下面有答题，也没有跳过功能 会卡住 希望大佬完善

**Comment by fw567** [comment]
> 
目前修复了倍速和静音功能，其他的bug暂时先不修，有空了再修。
